### PR TITLE
Upgrade nodejs-quickstart to new APIs versions

### PR DESCRIPTION
**Pull request by mgolebiowski**
After some upgrades in googleapi and google-auth-library this quickstart code stopped working. This changes get it back to a track.

### CODE REVIEW

**Comment by mgolebiowski** [comment]
As updates were applied by @AndyDiamondstein in 32f087d172e601cd02ecdcf207b5d076f603f1ac I'm closing this PR.

**Comment by hassan17hassan18** [comment]
https://youtu.be/Xwc5Rj5a1Dmm

**Comment by hassan17hassan18** [comment]
https://youtu.be/Xwc5Rj5a1FM

**Comment by hassan17hassan18** [comment]
http://youtu.be/Xwc5Rj5a1Dk

**Comment by hassan17hassan18** [comment]
https://youtu.be/d3uGnllCcYs

**Pull request closed without merging**
